### ISSUE TITLE
syncing cluster keep connecting/disconnecting from other peers

### ISSUE THREAD

**Issue by qcdll** [QuarkChain/pyquarkchain#211]
here is what I observed:
1. run a network (eg 5 clusters) and start mining, wait until it reaches some height
2. fire up a new cluster and connect to the network
3. the new cluster will connect with one peer (usually bootstrap node) and start syncing root blocks
4. while the new cluster is syncing, it will connect to other nodes in the network, but will close_with_error:
```
MASTER: E1127 10:57:41.764544 master.py:102] Traceback (most recent call last):
MASTER: File "master.py", line 100, in sync
MASTER: await self.__run_sync()
MASTER: File "master.py", line 164, in __run_sync
MASTER: await self.__add_block(block)
MASTER: File "master.py", line 207, in __add_block
MASTER: await self.master_server.add_root_block(root_block)
MASTER: File "master.py", line 1109, in add_root_block
MASTER: check(all([resp.error_code == 0 for _, resp, _ in result_list]))
MASTER: File "/Users/dll/chain/pyquarkchain/quarkchain/utils.py", line 61, in check
MASTER: raise AssertionError(msg)
MASTER: AssertionError
Closing peer XXX with the following reason:
```
it seems the slaves refused to add the root block in question because the prev root block is unknown

**Comment by qcdll** [comment]
this was due to incorrect genesis blocks: testnet alloc/loadtest accounts are different from public repo, so the connection would drop because genesis blocks do not match
