### ISSUE TITLE
syncing problem

### ISSUE THREAD

**Issue by chenhuan14** [QuarkChain/pyquarkchain#259]
After successfully synchronizing the blockchain, the cluster runs for a period of time and then enters the synchronization again, however, it will not finish sync this time,  so that we must restart the cluster to regain the latest state.

**Comment by chenhuan14** [comment]
more specific error:


cluster.py error output:
SLAVE_S2: E1210 13:07:36.023073 shard.py:547] Traceback (most recent call last):
SLAVE_S2: File "/code/pyquarkchain/quarkchain/cluster/shard.py", line 545, in add_block
SLAVE_S2: xshard_list = self.state.add_block(block)
SLAVE_S2: File "/code/pyquarkchain/quarkchain/cluster/shard_state.py", line 678, in add_block
SLAVE_S2: self.__validate_block(block)
SLAVE_S2: File "/code/pyquarkchain/quarkchain/cluster/shard_state.py", line 431, in __validate_block
SLAVE_S2: block.header.hash_prev_minor_block.hex(),
SLAVE_S2: ValueError: [2] prev block not found, block height 58080 prev hash b48ee795e5ee8b4c4344d94805764d2ab53e8fb3a798480b6303166

stats:
2018-12-10 12:54:06     False    7271 [57894, 57912, 57929, 57808, 57894, 57933, 57632, 57694]
2018-12-10 12:54:16     False    7271 [57894, 57912, 57929, 57808, 57894, 57933, 57632, 57694]
2018-12-10 12:54:26     False    7271 [57894, 57912, 57929, 57808, 57894, 57933, 57632, 57694]
2018-12-10 12:54:36      True    7271 [57894, 57912, 57929, 57808, 57894, 57933, 57632, 57694]
2018-12-10 12:54:46      True    7271 [57894, 57912, 57929, 57808, 57894, 57933, 57632, 57694]
2018-12-10 12:54:56      True    7271 [57894, 57912, 57929, 57808, 57894, 57933, 57632, 57694]
2018-12-10 12:55:06     False    7271 [57894, 57912, 57929, 57808, 57894, 57933, 57632, 57694]
2018-12-10 12:55:16     False    7271 [57894, 57912, 57929, 57808, 57894, 57933, 57632, 57694]
2018-12-10 12:55:26     False    7271 [57894, 57912, 57929, 57808, 57894, 57933, 57632, 57694]
2018-12-10 12:55:36     False    7271 [57894, 57912, 57929, 57808, 57894, 57933, 57632, 57694]
2018-12-10 12:55:46      True    7271 [57894, 57912, 57929, 57808, 57894, 57933, 57632, 57694]
2018-12-10 12:55:56     False    7271 [57894, 57912, 57929, 57808, 57894, 57933, 57632, 57694]
2018-12-10 12:56:06     False    7271 [57894, 57912, 57929, 57808, 57894, 57933, 57632, 57694]
2018-12-10 12:56:16     False    7271 [57894, 57912, 57929, 57808, 57894, 57933, 57632, 57694]
2018-12-10 12:56:26      True    7271 [57894, 57912, 57929, 57808, 57894, 57933, 57632, 57694]
2018-12-10 12:56:36      True    7271 [57894, 57912, 57929, 57808, 57894, 57933, 57632, 57694]
2018-12-10 12:56:46      True    7271 [57894, 57912, 57929, 57808, 57894, 57933, 57632, 57694]
2018-12-10 12:56:57      True    7271 [57894, 57912, 57929, 57808, 57894, 57933, 57632, 57694]
2018-12-10 12:57:07      True    7271 [57894, 57912, 57929, 57808, 57894, 57933, 57632, 57694]
2018-12-10 12:57:17      True    7271 [57894, 57912, 57929, 57808, 57894, 57933, 57632, 57694]
2018-12-10 12:57:27     False    7271 [57894, 57912, 57929, 57808, 57894, 57933, 57632, 57694]

it will in sync forever, never get right state.

**Comment by ninjaahhh** [comment]
most likely the cluster is trapped in a bad state during syncing. #293 may help in this case.

please report if the problem continues.

btw: restarting the cluster is the last resort but it usually works

**Comment by ninjaahhh** [comment]
close for now due to inactivity
