### ISSUE TITLE
missing add_block_future broke sync

### ISSUE THREAD

**Issue by qcgg** [QuarkChain/pyquarkchain#295]
Need to figure out how this block hash could be missing from the add_block_futures dict.

```
MASTER: I1220 07:54:21.509129 jsonrpc.py:412] {"jsonrpc": "2.0", "method": "submitWork", "params": ["0x6", "0x398d5851808368c966f9d7a35798787dbe5803e0ca83e483112ecce
cf2576fd1", "0xaad88b49f7150952", "0xfe40133419af93ffb629ff2c36f7aedf9e8a0c0e316da56075bd9d16209181c6"], "id": 50878}
MASTER: I1220 07:54:21.509669 jsonrpc.py:412] {"jsonrpc": "2.0", "method": "submitWork", "params": ["0x6", "0x398d5851808368c966f9d7a35798787dbe5803e0ca83e483112ecce
cf2576fd1", "0xe204f1df987605e2", "0xbae3e9c628e07730db2e59026d97fbf25fbdf93dcc6aa9effc3a27c700ae2aee"], "id": 55372}
SLAVE_S2: I1220 07:54:21.520933 shard.py:538] [6] got new block with height 55715
MASTER: I1220 07:54:21.537536 jsonrpc.py:412] {"jsonrpc": "2.0", "method": "getWork", "params": ["0x6"], "id": 55236}
MASTER: I1220 07:54:21.547801 jsonrpc.py:412] {"jsonrpc": "2.0", "method": "getWork", "params": ["0x7"], "id": 95213}
SLAVE_S2: ESC[1;31mE1220ESC[1;0m 07:54:21.550796 miner.py:308] Traceback (most recent call last):
SLAVE_S2: File "/code/pyquarkchain/quarkchain/cluster/miner.py", line 303, in submit_work
SLAVE_S2: await self.add_block_async_func(block)
SLAVE_S2: File "/code/pyquarkchain/quarkchain/cluster/shard.py", line 424, in __add_block
SLAVE_S2: await self.handle_new_block(block)
SLAVE_S2: File "/code/pyquarkchain/quarkchain/cluster/shard.py", line 542, in handle_new_block
SLAVE_S2: await self.add_block(block)
SLAVE_S2: File "/code/pyquarkchain/quarkchain/cluster/shard.py", line 593, in add_block
SLAVE_S2: self.add_block_futures[block.header.get_hash()].set_result(None)
SLAVE_S2: KeyError: b'\xc9\x06`?L\xf6\x84C\x1b\xa1j${]\x1b\xbcoJ\xdc\xcf\x15\xbb9\xfai\xb0B\xa7\x03.\x10"'
```

**Comment by qcgg** [comment]
Found the root cause
https://github.com/QuarkChain/pyquarkchain/blob/c4476439bd608b53e7b2ec4ef489f1fdac3451ca/quarkchain/cluster/miner.py#L301

The second submission of the same work changed the block header and resulted in a different hash.
