### ISSUE TITLE
add_block failed causing sync to stuck

### ISSUE THREAD

**Issue by qcgg** [QuarkChain/pyquarkchain#298]
```
SLAVE_S3: I1221 01:14:55.056043 shard.py:538] [7] got new block with height 62118
SLAVE_S3: E1221 01:14:55.077384 miner.py:309] Traceback (most recent call last):
SLAVE_S3: File "/code/pyquarkchain/quarkchain/cluster/miner.py", line 302, in submit_work
SLAVE_S3: await self.add_block_async_func(block)
SLAVE_S3: File "/code/pyquarkchain/quarkchain/cluster/shard.py", line 424, in __add_block
SLAVE_S3: await self.handle_new_block(block)
SLAVE_S3: File "/code/pyquarkchain/quarkchain/cluster/shard.py", line 542, in handle_new_block
SLAVE_S3: await self.add_block(block)
SLAVE_S3: File "/code/pyquarkchain/quarkchain/cluster/shard.py", line 590, in add_block
SLAVE_S3: self.state.get_shard_stats(),
SLAVE_S3: File "/code/pyquarkchain/quarkchain/cluster/shard_state.py", line 1371, in get_shard_stats
SLAVE_S3: while block.header.height > 0 and block.header.create_time > cutoff:
SLAVE_S3: AttributeError: 'NoneType' object has no attribute 'header'
SLAVE_S3: 
SLAVE_S3: E1221 01:14:55.078691 slave.py:1201] Traceback (most recent call last):
SLAVE_S3: File "slave.py", line 1199, in get_work
SLAVE_S3: return await shard.miner.get_work()
SLAVE_S3: File "/code/pyquarkchain/quarkchain/cluster/miner.py", line 256, in get_work
SLAVE_S3: block = await self.create_block_async_func(retry=False)
SLAVE_S3: File "/code/pyquarkchain/quarkchain/cluster/shard.py", line 415, in __create_block
SLAVE_S3: return self.state.create_block_to_mine(address=miner_address)
SLAVE_S3: File "/code/pyquarkchain/quarkchain/cluster/shard_state.py", line 995, in create_block_to_mine
SLAVE_S3: block = prev_block.create_block_to_append(
SLAVE_S3: AttributeError: 'NoneType' object has no attribute 'create_block_to_append'
SLAVE_S3: 
SLAVE_S3: E1221 01:14:55.128375 slave.py:1201] Traceback (most recent call last):
SLAVE_S3: File "slave.py", line 1199, in get_work
SLAVE_S3: return await shard.miner.get_work()
SLAVE_S3: File "/code/pyquarkchain/quarkchain/cluster/miner.py", line 256, in get_work
SLAVE_S3: block = await self.create_block_async_func(retry=False)
SLAVE_S3: File "/code/pyquarkchain/quarkchain/cluster/shard.py", line 415, in __create_block
SLAVE_S3: return self.state.create_block_to_mine(address=miner_address)
SLAVE_S3: File "/code/pyquarkchain/quarkchain/cluster/shard_state.py", line 995, in create_block_to_mine
SLAVE_S3: block = prev_block.create_block_to_append(
SLAVE_S3: AttributeError: 'NoneType' object has no attribute 'create_block_to_append'
SLAVE_S3: 
SLAVE_S3: E1221 01:14:55.215536 slave.py:1201] Traceback (most recent call last):
SLAVE_S3: File "slave.py", line 1199, in get_work
SLAVE_S3: return await shard.miner.get_work()
SLAVE_S3: File "/code/pyquarkchain/quarkchain/cluster/miner.py", line 256, in get_work
SLAVE_S3: block = await self.create_block_async_func(retry=False)
SLAVE_S3: File "/code/pyquarkchain/quarkchain/cluster/shard.py", line 415, in __create_block
SLAVE_S3: return self.state.create_block_to_mine(address=miner_address)
SLAVE_S3: File "/code/pyquarkchain/quarkchain/cluster/shard_state.py", line 995, in create_block_to_mine
SLAVE_S3: block = prev_block.create_block_to_append(
SLAVE_S3: AttributeError: 'NoneType' object has no attribute 'create_block_to_append'
```

**Comment by qcgg** [comment]
still looks like a race

**Comment by qcgg** [comment]
damn, copy.copy is shallow copy

**Comment by qcdll** [comment]
...
