### ISSUE TITLE
E0411 shard.py:53 Closing shard connection with error

### ISSUE THREAD

**Issue by Bambarello** [QuarkChain/pyquarkchain#480]
New errors appeared in the node log, see below. No config changes, node is in full sync.

```
SLAVE_S0: E0411 20:51:10.887883 shard.py:53] Closing shard connection with error
SLAVE_S3: E0411 20:51:13.733516 base_events.py:1274] Task exception was never retrieved
SLAVE_S3: future: <Task finished coro=<AbstractConnection.active_and_loop_forever() done, defined at /code/pyquarkchain/quarkchain/protocol.py:189> exception=InvalidStateError('invalid state',)>
SLAVE_S3: Traceback (most recent call last):
SLAVE_S3: File "/code/pyquarkchain/quarkchain/protocol.py", line 200, in active_and_loop_forever
SLAVE_S3: future.set_exception(RuntimeError("{}: connection abort".format(self.name)))
SLAVE_S3: asyncio.base_futures.InvalidStateError: invalid state
SLAVE_S0: E0411 20:51:14.227126 base_events.py:1274] Task exception was never retrieved
SLAVE_S0: future: <Task finished coro=<AbstractConnection.active_and_loop_forever() done, defined at /code/pyquarkchain/quarkchain/protocol.py:189> exception=InvalidStateError('invalid state',)>
SLAVE_S0: Traceback (most recent call last):
SLAVE_S0: File "/code/pyquarkchain/quarkchain/protocol.py", line 200, in active_and_loop_forever
SLAVE_S0: future.set_exception(RuntimeError("{}: connection abort".format(self.name)))
SLAVE_S0: asyncio.base_futures.InvalidStateError: invalid state
SLAVE_S0: E0411 20:51:14.229636 base_events.py:1274] Task exception was never retrieved
SLAVE_S0: future: <Task finished coro=<AbstractConnection.active_and_loop_forever() done, defined at /code/pyquarkchain/quarkchain/protocol.py:189> exception=InvalidStateError('invalid state',)>
SLAVE_S0: Traceback (most recent call last):
SLAVE_S0: File "/code/pyquarkchain/quarkchain/protocol.py", line 200, in active_and_loop_forever
SLAVE_S0: future.set_exception(RuntimeError("{}: connection abort".format(self.name)))
SLAVE_S0: asyncio.base_futures.InvalidStateError: invalid state
SLAVE_S0: E0411 20:51:14.239781 base_events.py:1274] Task exception was never retrieved
SLAVE_S0: future: <Task finished coro=<AbstractConnection.active_and_loop_forever() done, defined at /code/pyquarkchain/quarkchain/protocol.py:189> exception=InvalidStateError('invalid state',)>
SLAVE_S0: Traceback (most recent call last):
SLAVE_S0: File "/code/pyquarkchain/quarkchain/protocol.py", line 200, in active_and_loop_forever
SLAVE_S0: future.set_exception(RuntimeError("{}: connection abort".format(self.name)))
SLAVE_S0: asyncio.base_futures.InvalidStateError: invalid state
```

**Comment by qizhou** [comment]
Please share version info or git commit.

**Comment by qizhou** [comment]
BTW: is the cluster still syncing or shutdown?

**Comment by Bambarello** [comment]
The version: 2.5.5 (from within docker)
NB: cluster failed to continue synchronization after this finding, root blocks stopped, but cluster reported that the sync status is "False", so that was false-positive status of synchronization.

**Comment by Bambarello** [comment]
Additional comment, here is another sync error, looks caused by forked nodes around:

```
MASTER: W0412 06:58:04.738226 master.py:124] [R] abort syncing due to forking at super old block 38281 << 38683
MASTER: W0412 06:58:13.762901 master.py:124] [R] abort syncing due to forking at super old block 38293 << 38683
MASTER: W0412 06:58:14.831742 master.py:124] [R] abort syncing due to forking at super old block 38281 << 38683
SLAVE_S3: E0412 06:58:24.894390 shard.py:236] Traceback (most recent call last):
SLAVE_S3: File "/code/pyquarkchain/quarkchain/cluster/shard.py", line 234, in sync
SLAVE_S3: await self.__run_sync()
SLAVE_S3: File "/code/pyquarkchain/quarkchain/cluster/shard.py", line 291, in __run_sync
SLAVE_S3: self.__download_blocks(block_header_chain[:100]), TIMEOUT
SLAVE_S3: File "/usr/lib/python3.6/asyncio/tasks.py", line 362, in wait_for
SLAVE_S3: raise futures.TimeoutError()
SLAVE_S3: concurrent.futures._base.TimeoutError
SLAVE_S3:
SLAVE_S3: E0412 06:58:24.894747 shard.py:53] Closing shard connection with error
SLAVE_S3: E0412 06:58:27.591179 base_events.py:1274] Task exception was never retrieved
SLAVE_S3: future: <Task finished coro=<AbstractConnection.active_and_loop_forever() done, defined at /code/pyquarkchain/quarkchain/protocol.py:189> exception=InvalidStateError('invalid state',)>
SLAVE_S3: Traceback (most recent call last):
SLAVE_S3: File "/code/pyquarkchain/quarkchain/protocol.py", line 200, in active_and_loop_forever
SLAVE_S3: future.set_exception(RuntimeError("{}: connection abort".format(self.name)))
SLAVE_S3: asyncio.base_futures.InvalidStateError: invalid state
MASTER: W0412 06:58:35.553171 master.py:124] [R] abort syncing due to forking at super old block 38281 << 38683
MASTER: W0412 06:58:44.755560 master.py:124] [R] abort syncing due to forking at super old block 38293 << 38683
MASTER: W0412 06:58:48.920197 master.py:124] [R] abort syncing due to forking at super old block 38281 << 38683
MASTER: W0412 06:58:59.946446 master.py:124] [R] abort syncing due to forking at super old block 38281 << 38683

```

**Comment by qizhou** [comment]
It may not be fork, but it requests to sync from very old block, which may be the same as the selected chain, but current logic will stop the sync as it is too old.
